name: strapi-stack
services:
  - name: postgres
    runtime: docker
    image: postgres:15
    start:
      command: postgres
    network:
      ports:
        - name: db
          port: 5432
          public: false
    storage:
      - name: pgdata
        mountPath: /var/lib/postgresql/data
        size: 10Gi
    env:
      - name: POSTGRES_DB
        value: strapi
      - name: POSTGRES_USER
        value: strapi
      - name: POSTGRES_PASSWORD
        value: change_me_secure
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata

  - name: strapi
    runtime: nodejs18
    build:
      commands:
        - npm ci
        - npm run build
    start:
      command: npm start
    network:
      ports:
        - name: http
          port: 3001
          public: true
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "1337"
      - name: APP_KEYS
        value: "k1,k2,k3,k4"
      - name: API_TOKEN_SALT
        value: "change_me_secure"
      - name: ADMIN_JWT_SECRET
        value: "change_me_secure"
      - name: JWT_SECRET
        value: "change_me_secure"
      - name: DATABASE_CLIENT
        value: "postgres"
      - name: DATABASE_HOST
        value: "postgres"
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_NAME
        value: "strapi"
      - name: DATABASE_USERNAME
        value: "strapi"
      - name: DATABASE_PASSWORD
        value: "change_me_secure"
      - name: DATABASE_SSL
        value: "false"
