# Strapi CMS Production Configuration
# IMPORTANT: This service must be created as NEW on Render.com
# Do not update existing service - create new one!
services:
  - type: web
    name: strapi-cms-final-v2
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /admin
    autoDeploy: true
